controllers:
    resource: ../src/Controller/
    type: attribute

calendar:
    path: /calendar
    controller: App\Controller\CalendarController::index
calendar_afficher:
    path: /calendar/afficher
    controller: App\Controller\CalendarController::afficher
index:
    path: /
    controller: App\Controller\AccueilController::bonjour
newIntervenant_success:
    path: intervenant/newintersuccess
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'intervenant/static/success.html.twig'
        maxAge: 86400
        sharedAge: 86400